# Configurações para produção (usando variáveis de ambiente):
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${PORT:8080}

# Configurações para desenvolvimento local:
# ⚠️ ATENÇÃO: Esta senha é apenas para desenvolvimento local
# Para produção, use variáveis de ambiente (comentado acima)
# spring:
#   datasource:
#     url: jdbc:postgresql://localhost:5432/gerenciador_membros
#     username: postgres
#     password: 2505  # Senha local - NÃO usar em produção!
#   main:
#     allow-bean-definition-overriding: true
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#     properties:
#       hibernate.format_sql: true
#       hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

# server:
#   port: 8080 